spring.application.name=itookthese-project
spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate                                                            
spring.flyway.enabled=true
spring.jpa.open-in-view=false
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}