  server {
      listen 80;

      # serve Angular app
      location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
      }

      # proxy API requests
      location /api/ {
        proxy_pass http://api:8080;
      }
  }